name: Snyk Code SAST Scan

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

permissions:
  contents: read
  security-events: write
  actions: read

jobs:
  snyk-sast:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Snyk CLI
        uses: snyk/actions/setup@master
        env:
          SNYK_TOKEN: a1eb8b76-9f7f-4ff8-8fcb-e951abcdfa23

      - name: Run Snyk Code SAST Scan
        id: snyk-code
        run: |
          snyk code test --fail-on=high --sarif-file-output=snyk-code.sarif
        env:
          SNYK_TOKEN: a1eb8b76-9f7f-4ff8-8fcb-e951abcdfa23
        continue-on-error: true  # Ensure SARIF is generated even on failure

      - name: Upload SARIF to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk-code.sarif

      - name: Fail pipeline if high/critical vulnerabilities are found
        if: steps.snyk-code.outcome == 'failure'
        run: exit 1
